#!/bin/bash

cd ~/MPL-REU-2022/Data_Augmentation/occluded_data

for ((a=0; a<=1; a++))
do
	for ((b=0; b<=1; b++))
	do
		for ((c=0; c<=1; c++))
		do
			for ((d=0; d<=1; d++))
			do
				for ((e=0; e<=1; e++))
				do
					mkdir './'$a$b$c$d$e
				done
			done
		done
	done
done
